<?php
$z[0]=Array("array","@me = (empty(@me['litpic']) ? \"\" : \"<a href='{@me['arcurl']}' class='preview'><img src='{@me['litpic']}'/></a>\"); ",5,159);
$z[0][4]['runphp']="yes";
$z[1]=Array("typelink","",173,190);
$z[2]=Array("arcurl","",205,220);
$z[3]=Array("title","",236,250);
$z[4]=Array("pubdate","",282,328);
$z[4][4]['function']="GetDateTimeMK(@me)";
$z[5]=Array("click","",373,387);
$z[6]=Array("scores","",432,447);
$z[7]=Array("description","",489,509);

?>