<field:kcml itemname="课程目录" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:kcml>
<field:spdz itemname="视频地址" autofield="1" notsend="0" type="media" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:spdz>
<field:image itemname="图片" autofield="1" notsend="0" type="img" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:image>
<field:jiangshi itemname="讲师" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:jiangshi>
<field:shichang itemname="时长" autofield="1" notsend="0" type="text" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:shichang>
