<?php
$z[0]=Array("global","",127,159);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("type","<a href=\"[field:typelink /]\" target=\"_blank\">公开课</a>",312,401);
$z[1][4]['typeid']="1";
$z[2]=Array("type","<a href=\"[field:typelink /]\" target=\"_blank\">直播课</a>",420,511);
$z[2][4]['typeid']="180";
$z[3]=Array("type","<a href=\"[field:typelink /]\" target=\"_blank\">资讯</a>",530,617);
$z[3][4]['typeid']="2";
$z[4]=Array("type","<a href=\"[field:typelink /]\" target=\"_blank\">增值服务</a>",636,727);
$z[4][4]['typeid']="3";
$z[5]=Array("type","<a href=\"[field:typelink /]\">论坛</a>",835,908);
$z[5][4]['typeid']="183";
$z[6]=Array("global","",1045,1070);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1649,1677);
$z[7][4]['name']="cfg_memberurl";
$z[8]=Array("global","",1735,1763);
$z[8][4]['name']="cfg_memberurl";

?>